"""
tests/tune_nearest_sr.py
========================
Train/test harness for the video strategy (TzwJTfYgK5FAujgWfLNa+fO1C_jia-DY).

HARD RULES
----------
* Data = REAL M1 gold proxy only (`data/candles/real/`).  Never `data/candles/gold_m1_*`,
  which is generated by `replay_data.generate_synthetic_gold_m1` and is fiction.
* Every config is fit on the FIRST 70% of trading days (train) and reported once on the
  UNTOUCHED last 30% (test).  Nothing is selected on the test split - the table is sorted
  by train PF only, and the test column is shown purely as a holdout readout.
* Configs are theory-driven (values the trader actually described in the video), not a
  random hyperparameter sweep.  A config that only wins in-sample is reported as such.

Usage
-----
    PYTHONPATH=. python3 tests/tune_nearest_sr.py [--days N] [--only NAME ...]
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
import time
from pathlib import Path

sys.path[:0] = [str(Path(__file__).resolve().parent)]

from backtest_nearest_sr_video import AuditConfig, load_candles, run_backtest  # noqa: E402

# --------------------------------------------------------------------------
# Exit policy lives on AuditConfig (ratchet_*/stagnation_cut_secs/max_hold_secs);
# everything else strategy-side goes in strategy_kwargs.
#
# TARGET_ONLY = the video literally: close at the nearest opposing level or at
# the invalidation stop, nothing in between.  The peak ratchet and the
# stagnation cut are the harness's *additions*; they are switched off here and
# re-introduced as explicit live-behaviour variants below.
# --------------------------------------------------------------------------
TARGET_ONLY = dict(
    ratchet_arm_frac=1e18,
    ratchet_giveback_frac=1e18,
    stagnation_cut_secs=1e18,
)
LEVEL = dict(level_lookback=1440)          # 1 day of M1 ~ the trader's chart
# The video, literally: reaction zone with 6+ touches, target = nearest opposing
# level 8-11 pts away, stop just beyond the zone.
STRAT = dict(
    min_touches=6,                          # "more than six times"
    min_rr=3.0,                             # observed 3.1 and 4.7
    min_room_pts=8.0,                       # observed targets 8.1 - 10.9 pts away
    max_target_pts=12.0,
    sl_max_pts=3.0,                         # observed stops ~2.3 - 2.7 pts
    sl_buffer=0.55,
)
# The measured gap: with a thin M1 zone the default stop lands ~1 pt out (RR ~8,
# WR 19%) whereas the trader's stops were 2.3-2.7 pts (RR ~3-4).  These two knobs
# reproduce that geometry - sl_min_pts widens a stop that would otherwise sit too
# close to be structural.
STRAT_SL23 = dict(STRAT, sl_buffer=0.90, sl_min_pts=2.00, sl_max_pts=2.80)
# Wider target band -> far more candidates; rr floor lowered because the same
# 8+ pt room now has to clear a wider stop.
STRAT_BAND = dict(STRAT_SL23, min_room_pts=5.0, max_target_pts=16.0, min_rr=2.0)
RATCHET1 = dict(ratchet_arm_frac=1.0, ratchet_giveback_frac=0.5,
                stagnation_cut_secs=1e18)

# (name, AuditConfig kwargs, NearestSRStrategy kwargs)
CONFIGS = [
    ("shipped_defaults", {}, {}),                                  # live defaults as of this audit
    ("video_tight", dict(LEVEL, **TARGET_ONLY), dict(STRAT)),       # raw video, thin stop
    ("video_sl23", dict(LEVEL, **TARGET_ONLY), dict(STRAT_SL23)),
    ("video_sl23_band", dict(LEVEL, **TARGET_ONLY), dict(STRAT_BAND)),
    ("video_sl23_band_mt4", dict(LEVEL, **TARGET_ONLY),
     dict(STRAT_BAND, min_touches=4)),
    ("video_sl23_lb720", dict(level_lookback=720, **TARGET_ONLY), dict(STRAT_SL23)),
    ("video_sl23_lb2880", dict(level_lookback=2880, **TARGET_ONLY), dict(STRAT_SL23)),
    ("video_sl23_band_lb720", dict(level_lookback=720, **TARGET_ONLY), dict(STRAT_BAND)),
    # live-behaviour variants (ratchet re-introduced)
    ("video_sl23_ratchet1", dict(LEVEL, **RATCHET1), dict(STRAT_SL23)),
    ("video_sl23_liveexit", dict(LEVEL), dict(STRAT_SL23)),
    ("video_sl23_band_r1", dict(LEVEL, **RATCHET1), dict(STRAT_BAND)),
    ("mid_lb720", dict(level_lookback=720, **TARGET_ONLY),
     dict(min_touches=4, min_rr=2.0, min_room_pts=4.0, sl_max_pts=3.0)),

    # ---- stage 2: video rule 5 (break/retest flip) as a hard filter ------
    # Stage 1 found NOTHING positive on both splits: the raw entry/exit geometry
    # is a coin flip before costs.  The only structurally-positive slice in the
    # full-year breakdown was FLIP_BUY/FLIP_SELL (+14.4pt) against plain
    # SUPPORT/RESISTANCE bounces (-17.7pt), which is the trader's own fifth rule.
    ("flip1440", dict(LEVEL, **TARGET_ONLY), dict(STRAT_SL23, require_flip=True)),
    ("flip720", dict(level_lookback=720, **TARGET_ONLY),
     dict(STRAT_SL23, require_flip=True)),
    ("flip_lb2880", dict(level_lookback=2880, **TARGET_ONLY),
     dict(STRAT_SL23, require_flip=True)),
    ("flip_band720", dict(level_lookback=720, **TARGET_ONLY),
     dict(STRAT_BAND, require_flip=True)),
    ("flip1440_s714", dict(LEVEL, allowed_hours="7-14", **TARGET_ONLY),
     dict(STRAT_SL23, require_flip=True)),
    ("flip1440_s913", dict(LEVEL, allowed_hours="9-13", **TARGET_ONLY),
     dict(STRAT_SL23, require_flip=True)),
]


def _day(ts: float) -> str:
    return dt.datetime.fromtimestamp(ts, dt.timezone.utc).strftime("%Y-%m-%d")


def split_days(candles):
    days = sorted({_day(c["minute_ts"]) for c in candles})
    cut = days[max(1, int(len(days) * 0.70))]
    train = [c for c in candles if _day(c["minute_ts"]) < cut]
    test = [c for c in candles if _day(c["minute_ts"]) >= cut]
    return train, test, cut, len(days)


def row(name: str, res, tag: str) -> str:
    return (
        f"{name:<18}{tag:<7}{len(res.trades):>5}{res.win_rate:>7.1f}%"
        f"{res.pf:>7.2f}{res.net:>+11.2f}{res.balance:>11.2f}"
        f"{res.max_dd_pct:>8.1f}%{res.avg_hold_mins:>8.1f}{res.avg_rr_planned:>6.2f}"
        + ("  RUIN" if res.ruin else "")
    )


HEADER = (
    f"{'config':<18}{'split':<7}{'n':>5}{'wr':>7}{'pf':>7}{'net$':>11}"
    f"{'end$':>11}{'maxDD':>9}{'holdm':>8}{'rr':>6}"
)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", nargs="*", default=None)
    ap.add_argument("--data-dir", default="data/candles/real")
    ap.add_argument("--start-balance", type=float, default=14.36)
    ap.add_argument("--spread", type=float, default=0.15)
    ap.add_argument("--slippage", type=float, default=0.05)
    ap.add_argument("--session", default="7-18")
    args = ap.parse_args()

    candles = load_candles(Path(args.data_dir))
    train, test, cut, ndays = split_days(candles)
    print(f"\n{ndays} trading days | train {len(train)} bars (< {cut}) | "
          f"test {len(test)} bars (>= {cut})")
    print(f"start balance ${args.start_balance}  spread {args.spread}pt  "
          f"slippage {args.slippage}pt  session {args.session} UTC\n")

    selected = [(n, c, s) for (n, c, s) in CONFIGS
                if args.only is None or n in args.only]

    print(HEADER)
    print("-" * len(HEADER))
    results = []
    t0 = time.time()
    for name, cfg_kw, strat_kw in selected:
        base = dict(
            start_balance=args.start_balance,
            spread_pts=args.spread,
            slippage_pts=args.slippage,
            allowed_hours=args.session,
        )
        base.update(cfg_kw)
        try:
            rc = AuditConfig(strategy_kwargs=dict(strat_kw), **base)
        except TypeError as exc:                       # key moved / typo
            print(f"{name:<18}CONFIG ERROR: {exc}")
            continue
        t1 = time.time()
        try:
            r_tr = run_backtest(train, rc)
            r_te = run_backtest(test, rc)
        except Exception as exc:                       # typo'd kwarg, etc.
            print(f"{name:<18}ERROR: {type(exc).__name__}: {exc}\n")
            continue
        print(row(name, r_tr, "train"))
        print(row(name, r_te, "TEST"))
        print("-" * len(HEADER))
        results.append((name, r_tr, r_te))
        print(f"    ({time.time() - t1:.0f}s)\n")

    # ---- ranking is by TRAIN pf, subject to a minimum sample -----------
    usable = [t for t in results if len(t[1].trades) >= 8]
    print("\n=== ranked by TRAIN pf (n >= 8); TEST shown as holdout only ===")
    print(HEADER)
    print("-" * len(HEADER))
    for name, r_tr, r_te in sorted(usable, key=lambda t: -t[1].pf):
        print(row(name, r_tr, "train"))
        print(row(name, r_te, "TEST"))

    survivors = [t for t in usable if t[1].pf > 1.0 and t[2].pf > 1.0]
    print("\nconfigs positive on BOTH splits: "
          + (", ".join(t[0] for t in survivors) if survivors else "NONE"))
    print(f"total {time.time() - t0:.0f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
